[package]
name = "gitignores-updater"
version = "0.0.0"
publish = false
edition = "2018"

authors = ["FeÌlix Saparelli <felix@passcod.name>"]
license = "Apache-2.0 OR MIT"
description = "Updater for the gitignores crate"

[dependencies]
